ema/config/urls.py
from __future__ import absolute_import

from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from matrix import urls as matrix_urls
from profiles import urls as profile_urls
from profiles.views import index
from orga import urls as orga_urls
from telegram_bot import urls as bot_urls

urlpatterns = [
    # startpage
    url(r'^$', index, name='startpage'),
    # account app
    url(r'^account/', include(profile_urls, namespace="profiles")),
    # matrix app
    url(r'^matrix/', include(matrix_urls, namespace="matrix")),
    # orga app
    url(r'^orga/', include(orga_urls, namespace="orga")),
    # telegram bot
    url(r'^bot/', include(bot_urls, namespace="bot")),
    # admin tool
    url(r'^admin/', include(admin.site.urls)),
    # favicon
    url(r'^', include('favicon.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# static files und speicherung static files

ema/matrix/urls.py
"""URLs to connect views and stuff."""
from __future__ import absolute_import

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views
from .views import TopicCreate, TaskCreate, TaskUpdate, AjaxTaskDelete
from .views import TopicUpdate, TaskDelete, TopicDelete

# TODO unneccessary pages entfernen
urlpatterns = [
    # /matrix/
    url(r'^$', views.matrix, name='matrix'),
    # /matrix/addtopic
    url(r'^addtopic/$',
        login_required(TopicCreate.as_view()),
        name='addtopic'),
    # /matrix/5/
    url(r'^(?P<topic_id>[0-9]+)/$', views.topics, name='topics'),
    # /matrix/5/tasks
    url(r'^(?P<task_id>[0-9]+)/tasks/$', views.tasks, name='tasks'),
    # /matrix/5/adding
    url(r'^adding/$',
        login_required(TaskCreate.as_view()),
        name='adding'),
    # /matrix/5/edittopic
    url(r'^(?P<topic_id>[0-9]+)/edittopic/$',
        login_required(TopicUpdate.as_view()),
        name='topicediting'),
    # /matrix/5/deletetopic
    url(r'^(?P<topic_id>[0-9]+)/deletetopic/$',
        login_required(TopicDelete.as_view()),
        name='topicdeleting'),
    # /matrix/5/taskediting
    url(r'^(?P<task_id>[0-9]+)/taskediting/$',
        login_required(TaskUpdate.as_view()),
        name='taskediting'),
    # /matrix/5/taskdeleting
    url(r'^(?P<task_id>[0-9]+)/taskdeleting/$',
        login_required(TaskDelete.as_view()),
        name='taskdeleting'),
    # /matrix/done_tasks
    url(r'^done_tasks/$', views.done_tasks, name='done_tasks'),
    # ajax-urls
    # /matrix/5/taskdelete
    url(r'^(?P<task_id>[0-9]+)/taskdelete/$',
        login_required(AjaxTaskDelete.as_view()),
        name='taskdelete'),
]

ema/orga/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views

urlpatterns = [
    # /orga/about_ema
    url(r'^about_ema/$', views.about_ema, name='about_ema'),
    # /orga/impressum
    url(r'^impressum/$', views.impressum, name='impressum'),
    # /orga/help
    url(r'^help/$', views.help, name='help')
]

ema/profiles/urls.py
from __future__ import absolute_import

from django.contrib.auth.views import login, logout, password_change
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views
from .views import AccountSettings

urlpatterns = [
    # /account/
    url(r'^$', login_required(AccountSettings.as_view()), name='account'),
    # /account/login/
    url(r'^login/$', login, name='login'),
    # /account/loggedout/
    url(r'^loggedout/$', logout, name='loggedout'),
    # /account/register/
    url(r'^register/$', views.register, name='register'),
    # /account/passwordchange/
    # url(r'^passwordchange/$', views.update_password, name="passwordchange")
]

ema/telegram_bot/urls.py
from __future__ import absolute_import

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views
from .views import SetupBot

urlpatterns = [
    # /bot/start/
    url(r'^start/$', views.ema_authenticate, name='start'),
    # /bot/
    url(r'^telegrambot/$', login_required(SetupBot.as_view()), name='setup')
]

ema/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset='UTF-8'/>
    <title>
      {% block title %}
      {# different titles for different tabs, standard: #}
        Eisenhower Matrix
      {% endblock title %}
    </title>
    {% block stylesheets %}
    {# change stylesheets per tab #}
      <link rel="stylesheet" type="text/css"
            href={% static "css/bootstrap.min.css" %}>
      <link rel="stylesheet" type="text/css"
                  href={% static "css/stylesheet.css" %}>
    {% endblock stylesheets %}
    {% block js %}
      <script type="text/javascript" src={% static "js/jquery-2.1.4.min.js" %}>
      </script>
    {% endblock js %}
  </head>
  <body>
    {% block navbar %}
    {# changed in every template to match the current tab #}
    {% endblock navbar %}
    <div class="main">
      {% block messages %}
        <div class="messages" style="display: {% if messages %}block{% else %}none{% endif %};">
          <div class="text">
            {% if messages %}
              {% for message in messages %}
              <span>{{ message }}</span>
              {% endfor %}
            {% endif %}
          </div>
          <div class="closeX">
            <span class="closeNotification">x</span>
          </div>
        </div>
      {% endblock messages %}
      {% block content %}
      {# everything between header and footer #}
      {% endblock content %}
    </div>
    {% block javascript %}
    {# javascript only where needed -> matrix #}
      <script type="text/javascript" src={% static "js/bootstrap.min.js" %}>
      </script>
      <script type="text/javascript" src={% static "js/ema.js" %}></script>
    {% endblock javascript %}
  </body>
  {% block footer %}
  {# footer included in every template #}
  {% endblock footer %}
</html>

ema/templates/footer.html
{% load staticfiles %}
{% block footer %}
<footer>
  <div class="footer">
    <div class="emaNavbar">
      <ul>
        <li>
          <a class="navLink" href={% url 'orga:impressum' %}>
            <div class="{% if active_footer == 'Impressum' %}now{% endif %}">
              Impressum
            </div>
          </a>
        </li>
        <li>
          <a class="navLink" href={% url 'orga:about_ema' %}>
            <div class="{% if active_footer == 'About' %}now{% endif %}">
              About EMA
            </div>
          </a>
        </li>
        <!--li class="gap">
          <a class="navLink" href="http://www.facebook.com/ematrixapp">
            Find us on facebook:
            <span class="glyphicon glyphicon-facebook"></span>
          </a>
        </li-->
      </ul>
    </div>
  </div>
</footer>
{% endblock footer %}

ema/templates/matrix_base.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}EMA{% endblock title %}
{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href={% static "css/matrix.css" %}>
  <link rel="stylesheet" type="text/css" href={% static "css/calendar.css" %}>
{% endblock stylesheets %}
{% block navbar %}
  {% include "navbar.html" with active_tab='EMA' %}
{% endblock navbar %}
{% block footer %}
  {% include "footer.html" %}
{% endblock footer %}

ema/templates/navbar.html
{# variable active_tab to reduce redundance, activates the class now to #}
{# hightlight current tab #}
{% block navbar %}
<div class="emaNavbar navbar-fixed-top">
  <ul>
    <li>
      <!-- https://djangosnippets.org/snippets/2421/ navbar DRY method -->
      <a class="navLink" href={% url 'matrix:matrix' %}>
        <div class="{% if active_tab == 'EMA' %}now{% endif %}">HOME - EMA</div>
      </a>
    </li>
    <li>
      <a class="navLink" href={% url 'profiles:account' %}>
        <div class="{% if active_tab == 'Account' %}now{% endif %}">Account</div>
      </a>
    </li>
    <li>
      <a class="navLink" href={% url 'bot:setup' %}>
        <div class="{% if active_tab == 'Telegram' %}now{% endif %}">
          Telegram Bot
        </div>
      </a>
    </li>
    <li>
      <a class="navLink" href={% url 'orga:help' %}>
        <div class="{% if active_tab == 'Help' %}now{% endif %}">Help</div>
      </a>
    </li>
    <li class="gap">
      {% if user.is_anonymous %}
      {% else %}
      <a class="navLink userNavLink" href={% url 'profiles:account' %}>
        <div>{{ user }}</div>
      </a>
      {% endif %}
      {% if user.is_anonymous %}
      <a class="navLink" href={% url 'profiles:register' %}>
        <div class="{% if active_tab == 'Signup' %}now{% endif %}">Sign Up</div>
      </a>
    </li>
    <li>
      <a class="navLink" href={% url 'profiles:login' %}>
        <div class="{% if active_tab == 'Login' %}now{% endif %}">Log In</div>
      </a>
      {% else %}
      <a class="navLink" href={% url 'profiles:loggedout' %}>
        <div class="{% if active_tab == 'Logout' %}now{% endif %}">Log Out</div>
      </a>
      {% endif %}
    </li>
  </ul>
</div>
{% endblock navbar %}