ema/config/urls.py
from __future__ import absolute_import

from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from matrix import urls as matrix_urls
from profiles import urls as profile_urls
from profiles.views import index
from orga import urls as orga_urls
from telegram_bot import urls as bot_urls

urlpatterns = [
    # startpage
    url(r'^$', index, name='startpage'),
    # account app
    url(r'^account/', include(profile_urls, namespace="profiles")),
    # matrix app
    url(r'^matrix/', include(matrix_urls, namespace="matrix")),
    # orga app
    url(r'^orga/', include(orga_urls, namespace="orga")),
    # telegram bot
    url(r'^bot/', include(bot_urls, namespace="bot")),
    # admin tool
    url(r'^admin/', include(admin.site.urls)),
    # favicon
    url(r'^', include('favicon.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# static files und speicherung static files

ema/matrix/urls.py
"""URLs to connect views and stuff."""
from __future__ import absolute_import

from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views
from .views import TopicCreate, TaskCreate, TaskUpdate, AjaxTaskDelete
from .views import TopicUpdate, TaskDelete, TopicDelete

# TODO unneccessary pages entfernen
urlpatterns = [
    # /matrix/
    url(r'^$', views.matrix, name='matrix'),
    # /matrix/addtopic
    url(r'^addtopic/$',
        login_required(TopicCreate.as_view()),
        name='addtopic'),
    # /matrix/5/
    url(r'^(?P<topic_id>[0-9]+)/$', views.topics, name='topics'),
    # /matrix/5/tasks
    url(r'^(?P<task_id>[0-9]+)/tasks/$', views.tasks, name='tasks'),
    # /matrix/5/adding
    url(r'^adding/$',
        login_required(TaskCreate.as_view()),
        name='adding'),
    # /matrix/5/edittopic
    url(r'^(?P<topic_id>[0-9]+)/edittopic/$',
        login_required(TopicUpdate.as_view()),
        name='topicediting'),
    # /matrix/5/deletetopic
    url(r'^(?P<topic_id>[0-9]+)/deletetopic/$',
        login_required(TopicDelete.as_view()),
        name='topicdeleting'),
    # /matrix/5/taskediting
    url(r'^(?P<task_id>[0-9]+)/taskediting/$',
        login_required(TaskUpdate.as_view()),
        name='taskediting'),
    # /matrix/5/taskdeleting
    url(r'^(?P<task_id>[0-9]+)/taskdeleting/$',
        login_required(TaskDelete.as_view()),
        name='taskdeleting'),
    # /matrix/done_tasks
    url(r'^done_tasks/$', views.done_tasks, name='done_tasks'),
    # ajax-urls
    # /matrix/5/taskdelete
    url(r'^(?P<task_id>[0-9]+)/taskdelete/$',
        login_required(AjaxTaskDelete.as_view()),
        name='taskdelete'),
]

ema/orga/urls.py
from __future__ import absolute_import

from django.conf.urls import url

from . import views

urlpatterns = [
    # /orga/about_ema
    url(r'^about_ema/$', views.about_ema, name='about_ema'),
    # /orga/impressum
    url(r'^impressum/$', views.impressum, name='impressum'),
    # /orga/help
    url(r'^help/$', views.help, name='help')
]

ema/matrix/models.py
"""Definiere Models Topic und Task."""
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models


class TimeStampedModel(models.Model):
    """
    meta class for the fields created and modified.

    An abstract base class model that provides self-updating ''created''
    and ''modified'' fields.
    @source: 2scoops, page: 66
    """

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        """define abstract to inherit in other models."""

        abstract = True


class Topic(TimeStampedModel):
    """
    define model Topic.

    Fremdschluessel: topic owner
    Name
    Beschreibung
    Farben
    """

    topic_owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    topic_name = models.CharField(max_length=30)
    topic_description = models.TextField(max_length=2000, blank=True)
    # colors plus displayed names
    BLACK = 'black'
    GREY = 'grey'
    ROSYBROWN = 'rosybrown'
    SADDLEBROWN = 'saddlebrown'
    CRIMSON = 'crimson'
    ORANGERED = 'orangered'
    DARKORANGE = 'darkorange'
    GOLD = 'gold'
    YELLOWGREEN = 'yellowgreen'
    OLIVEDRAB = 'olivedrab'
    FORESTGREEN = 'forestgreen'
    DARKTURQUOISE = 'darkturquoise'
    DODGERBLUE = 'dodgerblue'
    ROYALBLUE = 'royalblue'
    MEDIUMBLUE = 'mediumblue'
    HOTPINK = 'hotpink'
    DEEPPINK = 'deeppink'
    MEDIUMVIOLETRED = 'mediumvioletred'
    PURPLE = 'purple'
    REBECCAPURPLE = 'rebeccapurple'
    MEDIUMORCHID = 'mediumorchid'
    COLOR_OPTIONS = [
        (BLACK, 'black'),
        (GREY, 'grey'),
        (ROSYBROWN, 'rosybrown'),
        (SADDLEBROWN, 'brown'),
        (CRIMSON, 'red'),
        (ORANGERED, 'orangered'),
        (DARKORANGE, 'orange'),
        (GOLD, 'yellow'),
        (YELLOWGREEN, 'lightgreen'),
        (OLIVEDRAB, 'olive'),
        (FORESTGREEN, 'green'),
        (DARKTURQUOISE, 'turquoise'),
        (DODGERBLUE, 'lightblue'),
        (ROYALBLUE, 'royalblue'),
        (MEDIUMBLUE, 'blue'),
        (HOTPINK, 'pink'),
        (DEEPPINK, 'deeppink'),
        (MEDIUMVIOLETRED, 'violet'),
        (PURPLE, 'purple'),
        (REBECCAPURPLE, 'darkpurple'),
        (MEDIUMORCHID, 'orchid'),
    ]
    color = models.CharField(
        max_length=15,
        choices=COLOR_OPTIONS,
        default=BLACK
    )

    def __unicode__(self):
        """Attribut, das bei Aufruf angezeigt wird."""
        return self.topic_name

    def get_absolute_url(self):
        """Referenzierung der einzelnen Instanzen ueber absolute URL."""
        return reverse('matrix:topics', kwargs={'topic_id': self.pk})


class Task(TimeStampedModel):
    """
    define model Task.

    Fremdschluessel: Topic: Topic
    Name: String (max=50)
    Beschreibung: String (max=3000)
    Wichtigkeit: String
    Due Date
    Erledigt
    Duration
    """

    # TODO Zahlen bei Importance
    task_name = models.CharField(max_length=50)
    task_description = models.TextField(max_length=3000, blank=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    NOT_IMPORTANT = 0
    LESS_IMPORTANT = 1
    IMPORTANT = 2
    VERY_IMPORTANT = 3
    IMPORTANCE_OPTIONS = (
        (NOT_IMPORTANT, 'not important'),
        (LESS_IMPORTANT, 'less important'),
        (IMPORTANT, 'important'),
        (VERY_IMPORTANT, 'very important'),
    )
    importance = models.IntegerField(
        choices=IMPORTANCE_OPTIONS,
        default=LESS_IMPORTANT
    )
    due_date = models.DateTimeField(auto_now=False, auto_now_add=False)
    done = models.BooleanField(default=False)
    duration = models.FloatField(blank=True, null=False, default=1)

    def __unicode__(self):
        """Attribut, das bei Aufruf angezeigt wird."""
        return self.task_name

    def get_absolute_url(self):
        """Referenzierung der einzelnen Instanzen ueber absolute URL."""
        return reverse('matrix:tasks', kwargs={'task_id': self.pk})

ema/matrix/views.py
"""Connect parts, called by urls.py."""
import json
from django.shortcuts import get_object_or_404, render
from django.views.generic import View
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.forms.models import model_to_dict
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.views import redirect_to_login

from orga.models import UserOrga

from .models import Topic, Task
from .forms import TaskForm, TopicForm
from .utils import get_user_colors

# TODO was wird noch gebraucht was nicht?


@login_required()
def matrix(request):
    """
    To display taks and topics.

    provides:
        - all topics in django and in JSON
        - all tasks in django and in JSON
        - settings of current user
    """
    # alle Topics
    all_topics = Topic.objects.filter(topic_owner=request.user.id)
    to_data = {}
    # alle Topics als JSON
    data = [model_to_dict(instance) for instance in all_topics]
    to_data['topics'] = data
    topic_data = json.dumps(to_data, cls=DjangoJSONEncoder)
    # alle Aufgaben
    all_tasks = Task.objects.filter(
        topic__topic_owner=request.user.id,
        done=False
    )
    # alle Aufgaben als JSON
    data = [model_to_dict(instance) for instance in all_tasks]
    end_data = json.dumps(data, cls=DjangoJSONEncoder)
    # Forms
    task_form = TaskForm(user=request.user)
    # Settings
    try:
        settings_file = UserOrga.objects.get(owner=request.user)
    except UserOrga.DoesNotExist:
        settings_file = UserOrga.objects.create(owner=request.user)
        settings_file.save()
    return render(
        request,
        'matrix/matrix.html',
        {'all_topics': all_topics, 'end_data': end_data,
            'topic_data': topic_data, 'task_form': task_form,
            'settings_file': settings_file}
    )


class AjaxableResponseMixin(object):
    """
    Mixin to add AJAX support to a form.

    Must be used with an object-based FormView (e.g. CreateView)
    @source: django docs
    https://docs.djangoproject.com/en/1.8/topics/class-based-views/generic-editing/
    """

    def form_invalid(self, form):
        """Response bei Fehler."""
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        # Fehler uebergeben, korrekter Statuscode fuer die Behandlung mit AJAX
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        """Response bei gueltigen Daten."""
        response = super(AjaxableResponseMixin, self).form_valid(form)
        # bei AJAX werden nur nur ein JSON-Objekt der Aufgaben uebergeben
        if self.request.is_ajax():
            topic = form.instance.topic_id
            all_tasks = Task.objects.filter(
                topic__topic_owner=self.request.user.id,
                done=False)
            response_data = json.dumps(
                [model_to_dict(instance) for instance in all_tasks],
                cls=DjangoJSONEncoder)
            return HttpResponse(response_data, content_type="application/json")
        else:
            return response


class PermissionDeniedMixin(object):
    """Verhindert den Zugriff auf Objekte, die nicht dem User gehoeren."""

    def users_object_test(self, request):
        """Testen, ob das Objekt dem User gehoert."""
        self.object = self.get_object()
        if isinstance(self.object, Topic):
            return self.object.topic_owner == request.user
        if isinstance(self.object, Task):
            return self.object.topic.topic_owner == request.user

    def dispatch(self, request, *args, **kwargs):
        """Weiterleiten oder Abblocken."""
        if not self.users_object_test(request):
            messages.info(request, "Permission Denied!")
            return redirect_to_login(request.get_full_path())
        return super(PermissionDeniedMixin, self).dispatch(
            request, *args, **kwargs)


class AjaxSuccessMessageMixin(SuccessMessageMixin):
    """Override django SuccessMessageMixin fuer AJAX Requests."""

    def get_success_message(self, cleaned_data):
        """Verhindern der success message bei AJAX-Requests."""
        if self.request.is_ajax():
            return None
        else:
            return self.success_message % cleaned_data


class TaskCreate(
        AjaxableResponseMixin,
        AjaxSuccessMessageMixin,
        CreateView):
    """
    Erstellt eine Aufgabe.

    mit AJAX verwendbar
    ruft die TaskForm mit dem zusaetzlichen Parameter user auf
    """

    model = Task
    form_class = TaskForm
    # template_name = 'matrix/adding.html'
    success_message = "Task '%(task_name)s' was successfully created!"
    success_url = '/matrix/'

    def get_form_kwargs(self):
        """Add user to form kwargs."""
        kwargs = super(TaskCreate, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class TaskUpdate(
        AjaxableResponseMixin,
        AjaxSuccessMessageMixin,
        PermissionDeniedMixin,
        UpdateView):
    """
    Bearbeitet Aufgabe.

    mit AJAX oder mit normalem Request verwendbar
    ruft die TaskForm mit dem zusaetzlichen Parameter user auf
    """

    model = Task
    form_class = TaskForm
    template_name = 'matrix/taskediting.html'
    success_message = "Task '%(task_name)s' was successfully modified!"
    success_url = '/matrix/'

    def get_object(self):
        """Richtige Aufgabe abrufen."""
        return get_object_or_404(Task, pk=self.kwargs.get('task_id'))

    def get_form_kwargs(self):
        """User zu den Form Kwargs hinzufuegen."""
        kwargs = super(TaskUpdate, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class TaskDelete(SuccessMessageMixin, PermissionDeniedMixin, DeleteView):
    """
    Loescht eine Aufgabe.

    nur fuer normale Requests
    """

    model = Task
    success_message = "Task '%(task_name)s' was successfully deleted!"
    success_url = '/matrix/'

    def get_object(self):
        """Richtige Aufgabe abrufen."""
        return get_object_or_404(Task, pk=self.kwargs.get('task_id'))


class AjaxTaskDelete(PermissionDeniedMixin, SingleObjectMixin, View):
    """
    Loescht eine Aufgabe.

    nur fuer AJAX-Requests
    """

    model = Task

    def get_object(self):
        """Richtige Aufgabe abrufen."""
        return Task.objects.get(pk=self.kwargs.get('task_id'))
        # TODO do i really have to check this?

    def post(self, *args, **kwargs):
        """Override post to delete right task with AJAX."""
        self.object = self.get_object()
        self.object.delete()
        all_tasks = Task.objects.filter(
            topic__topic_owner=self.request.user.id,
            done=False)
        response_data = json.dumps(
            [model_to_dict(instance) for instance in all_tasks],
            cls=DjangoJSONEncoder)
        return HttpResponse(response_data, content_type="application/json")


class TopicCreate(SuccessMessageMixin, CreateView):
    """
    Erstellt ein Thema.

    nicht fuer AJAX-Requests
    ruft das TopicForm mit dem zusaetzlichen Parameter user auf
    """

    model = Topic
    form_class = TopicForm
    template_name = 'matrix/addtopic.html'
    success_message = "Topic '%(topic_name)s' was successfully created!"
    success_url = '/matrix/'

    def get_form_kwargs(self):
        """Add User to form kwargs."""
        kwargs = super(TopicCreate, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class TopicUpdate(SuccessMessageMixin, PermissionDeniedMixin, UpdateView):
    """
    Bearbeitet ein Thema.

    nicht fuer AJAX-Requests
    ruft das TopicForm mit dem zusaetzlichen Parameter user auf
    """

    model = Topic
    form_class = TopicForm
    template_name = 'matrix/topicediting.html'
    success_message = "Topic '%(topic_name)s' was successfully edited!"
    success_url = '/matrix/'

    def get_form_kwargs(self):
        """Add User to form kwargs."""
        kwargs = super(TopicUpdate, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_object(self):
        """Richtige Topic abrufen."""
        return get_object_or_404(Topic, pk=self.kwargs.get('topic_id'))


class TopicDelete(PermissionDeniedMixin, DeleteView):
    """
    Loescht ein Thema.

    nicht fuer AJAX-Requests
    """

    model = Topic
    success_url = '/matrix/'

    def post(self, request, *args, **kwargs):
        """Delete cascade in models.py."""
        messages.info(
            request,
            'Topic "%s" successfully deleted.' % self.get_object())
        return self.delete(request, *args, **kwargs)

    def get_object(self):
        """Richtiges Topic abrufen."""
        return get_object_or_404(Topic, pk=self.kwargs.get('topic_id'))


@login_required()
def topics(request, topic_id):
    """
    To show the requested topic.

    @params: topic_id
    Permission denied message if unsuccessful
    """
    topic = get_object_or_404(Topic, pk=topic_id)
    if topic.topic_owner == request.user:
        return render(request, 'matrix/topic.html', {'topic': topic})
    else:
        messages.info(request, 'Permission denied!')
        return HttpResponseRedirect('/matrix/')


@login_required()
def tasks(request, task_id):
    """
    To show the requested task details.

    @params: task_id
    Permission denied message if unsuccessful
    """
    task = get_object_or_404(Task, pk=task_id)
    if task.topic.topic_owner == request.user:
        return render(request, 'matrix/task.html', {'task': task})
    else:

ema/templates/matrix/addtopic.html
{% extends "matrix_base.html" %}
{% load staticfiles %}
{% block js %}
<script type="text/javascript" src={% static "js/jquery-2.1.4.min.js" %}></script>
{% endblock js %}
{% block content %}
<div class="back">
  <a class="btn emaButton emaTask topicButton backButton" href={% url 'matrix:matrix' %}>< back</a>
</div>
<h1>Add a new topic:</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form class="emaForm" action="{% url 'matrix:addtopic' %}" method="post">
  {% csrf_token %}
  {{ form.non_field_errors }}
  <div class="fieldWrapper form-group">
    <label for="{{ form.topic_name.id_for_label }}">Topic Name:</label>
    {{ form.topic_name }}
    {{ form.topic_name.errors }}
  </div>
  <div class="fieldWrapper form-group">
    <label for="{{ form.topic_description.id_for_label }}">Topic Description:</label>
    {{ form.topic_description }}
    {{ form.topic_description.errors }}
  </div>
  <div class="fieldWrapper form-group">
    <label for="{{ form.color.id_for_label }}">Topic Color:</label>
    <ul class="noBottomMargList noListStyle">
      {% for choice in form.color.field.choices %}
        <li class="selectionList">
          <label for="id_{{ form.color.html_name }}_{{ forloop.counter0 }}">
            {% if choice.0 == form.color.value %}
            <div class="colorSelection" style="background-color: {{ form.color.value }}; border: 2px solid black"
                  onclick="$('.colorSelection').css('border', '2px solid #eee'); $('#id_{{ form.color.html_name }}_{{ forloop.counter0 }}').parent('div').css('border', '2px solid black');">
              <input type="radio"
                id="id_{{ form.color.html_name }}_{{ forloop.counter0 }}"
                value="{{ choice.0 }}"
                name="{{ form.color.html_name }}" />
            </div>
            {% else %}
            <div class="colorSelection" style="background-color: {{ choice.0 }}"
                  onclick="$('.colorSelection').css('border', '2px solid #eee'); $('#id_{{ form.color.html_name }}_{{ forloop.counter0 }}').parent('div').css('border', '2px solid black');">
              <input type="radio"
                id="id_{{ form.color.html_name }}_{{ forloop.counter0 }}"
                value="{{ choice.0 }}"
                name="{{ form.color.html_name }}" />
            </div>
            {% endif %}
          </label>
        </li>
      {% endfor %}
    </ul>
    {{ form.color.errors }}
  </div>
  <input class="btn emaButton emaNormal" type="submit" value="add topic" />
</form>
{% endblock content %}

ema/templates/matrix/done_tasks.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block navbar %}
  {% include "navbar.html" with active_tab='EMA' %}
{% endblock navbar %}
{% block content %}
<div>
  <h1>These are your accomplished tasks!</h1>
  <ul class="noListStyle">
  {% if dones %}
    {% for done in dones %}
      <li><a href={% url 'matrix:taskediting' done.id %}>{{ done.task_name }}</a></li>
    {% endfor %}
  {% else %}
    <li>
      <p>
        No finished tasks yet! Come on, get stuff done ;)
      </p>
    </li>
  {% endif %}
  </ul>
</div>
{% endblock content %}
{% block footer %}
  {% include "footer.html" %}
{% endblock footer %}

ema/templates/matrix/task.html
{% extends "matrix_base.html" %}
{% block content %}
<h1>{{ task.task_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<ul class="noListStyle">
  <li><small>Task Description:</small> {{ task.task_description }}</li>
  <li><small>Topic:</small> {{ task.topic }}</li>
  <li><small>Importance:</small> {{ task.get_importance_display }}</li>
  <li><small>Due Date:</small> {{ task.due_date }}</li>
  <li><small>Task was created:</small> {{ task.created }}</li>
  <li><small>Done?</small> {% if task.done == False %}no{% else %}yes{% endif %}</li>
</ul>

<a class="btn emaButton btn-success"
    href={% url 'matrix:taskediting' task.id %}>
  edit this task
</a>

<a class="btn emaButton btn-danger"
    href={% url 'matrix:taskdeleting' task.id %}>
  delete this task
</a>
{% endblock content %}

ema/templates/matrix/task_confirm_delete.html
{% extends 'matrix_base.html' %}
{% load staticfiles %}
{% block content %}
<h1>Are you sure you want to delete this task?</h1>
<ul class="noListStyle">
  <li><small>Task Name:</small> {{ task.task_name }}</li>
  <li><small>Task Description:</small> {{ task.task_description }}</li>
  <li><small>Topic:</small> {{ task.topic }}</li>
  <li><small>Importance:</small> {{ task.get_importance_display }}</li>
  <li><small>Due Date:</small> {{ task.due_date }}</li>
  <li><small>Task was created:</small> {{ task.created }}</li>
  <li><small>Done?</small> {% if task.done == False %}no{% else %}yes{% endif %}</li>
</ul>
<form action="" method="post">{% csrf_token %}
    <input class="btn emaButton btn-danger" type="submit" value="confirm" />
    <a class="btn emaButton emaNormal" href={% url 'matrix:taskediting' object.id %}>cancel</a>
</form>
{% endblock content %}

ema/templates/matrix/topic.html
{% extends "matrix_base.html" %}
{% block content %}
<h1 style="color: {{ topic.color }};">{{ topic.topic_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if topic.task_set.count > 0 %}
  <ul>
    {% for task in topic.task_set.all %}
      <li class="task_list"><a href={% url 'matrix:tasks' task.id %}>{{ task.task_name }}</a></li>
    {% endfor %}
  </ul>
{% endif %}
<a class="btn emaButton btn-primary" href={% url 'matrix:adding' %}>
  add a task
</a>
<a class="btn emaButton btn-success"
    href={% url 'matrix:topicediting' topic.id %}>
  edit this topic
</a>
<a class="btn emaButton btn-danger"
    href={% url 'matrix:topicdeleting' topic.id %}>
  delete this topic
</a>
{% endblock content %}

ema/templates/matrix/topic_confirm_delete.html
{% extends 'matrix_base.html' %}
{% load staticfiles %}
{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <p>This will delete all the topic's tasks!</p>
  <input class="btn emaButton btn-danger" type="submit" value="Confirm" />
  <a class="btn emaButton emaNormal" href={% url 'matrix:topics' object.id %}>cancel</a>
</form>
{% endblock content %}

ema/templates/matrix/topicediting.html
{% extends "matrix_base.html" %}
{% block content %}
<div class="row">
  <div class="col-lg-8">
    <h1>You are editing topic "{{ topic.topic_name }}"</h1>
    <form class="emaForm emaFormTopic" action="" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="form-group">
        <label for="{{ form.topic_name.id_for_label }}">Topic Name:</label>
        {{ form.topic_name }}
        {{ form.topic_name.errors }}
      </div>
      <div class="form-group">
        <label for="{{ form.topic_description.id_for_label }}">Topic Description:</label>
        {{ form.topic_description }}
        {{ form.topic_description.errors }}
      </div>
      <div class="form-group">
        <label for="{{ form.color.id_for_label }}">Topic Color:</label>
        <ul class="noBottomMargList noListStyle">
          {% for choice in form.color.field.choices %}
            <li class="selectionList">
              <label for="id_{{ form.color.html_name }}_{{ forloop.counter0 }}">
                {% if choice.0 == form.color.value %}
                <div class="colorSelection" style="background-color: {{ form.color.value }}; border: 2px solid black"
                      onclick="$('.colorSelection').css('border', '2px solid #eee'); $('#id_{{ form.color.html_name }}_{{ forloop.counter0 }}').parent('div').css('border', '2px solid black');">
                  <input type="radio"
                    id="id_{{ form.color.html_name }}_{{ forloop.counter0 }}"
                    value="{{ choice.0 }}"
                    name="{{ form.color.html_name }}" />
                </div>
                {% else %}
                <div class="colorSelection" style="background-color: {{ choice.0 }}"
                      onclick="$('.colorSelection').css('border', '2px solid #eee'); $('#id_{{ form.color.html_name }}_{{ forloop.counter0 }}').parent('div').css('border', '2px solid black');">
                  <input type="radio"
                    id="id_{{ form.color.html_name }}_{{ forloop.counter0 }}"
                    value="{{ choice.0 }}"
                    name="{{ form.color.html_name }}" />
                </div>
                {% endif %}
              </label>
            </li>
          {% endfor %}
        </ul>
        {{ form.color.errors }}
      </div>
      <input class="btn emaButton emaNormal" type="submit" value="edit topic" />
      <a class="btn emaButton btn-danger" href={% url 'matrix:topicdeleting' topic.id %}>
        delete topic
      </a>
    </form>
  </div>
  <div class="col-lg-4">
    <h2>Tasks for this topic:</h2>
    {% if topic.task_set.count > 0 %}
      <ul class="noListStyle">
        {% for task in topic.task_set.all %}
          <li class="task_list">
            <a href={% url 'matrix:tasks' task.id %}>{{ task.task_name }}</a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>no tasks yet</p>
      <!--<a class="btn emaButton emaNormal" href={% url 'matrix:adding' %}>add a task</a>-->
      <p>
        go to the EMA and add one!
      </p>
    {% endif %}
  </div>
</div>
{% endblock content %}